#pragma once

/*
 * Hardware wiring that must travel with source control.
 * Keep Wi-Fi/API secrets in local sdkconfig, but do not rely on ignored
 * sdkconfig for board-level GPIO assignments.
 */

#define APP_BOARD_LIGHT_STRIP_ENABLE 1
#define APP_BOARD_LIGHT_STRIP_GPIO 21
#define APP_BOARD_LIGHT_STRIP_ACTIVE_HIGH 1
#define APP_BOARD_LIGHT_STRIP_DEFAULT_LIGHT_MIN_LUX 200
#define APP_BOARD_LIGHT_STRIP_DEFAULT_LIGHT_MAX_LUX 2700
#define APP_BOARD_LIGHT_STRIP_ON_CONFIRM_MS 5000
#define APP_BOARD_LIGHT_STRIP_OFF_CONFIRM_MS 5000
#define APP_BOARD_LIGHT_STRIP_MIN_ON_MS 0
#define APP_BOARD_LIGHT_STRIP_MIN_OFF_MS 0
#define APP_BOARD_LIGHT_STRIP_OFF_PERIOD_ENABLED 0
#define APP_BOARD_LIGHT_STRIP_OFF_START_MINUTE (23 * 60)
#define APP_BOARD_LIGHT_STRIP_OFF_END_MINUTE (7 * 60)

#define APP_BOARD_WAKENET_ENABLE 1
#define APP_BOARD_VOICE_WAKE_THRESHOLD 120
#define APP_BOARD_VOICE_WAKE_THRESHOLD_MAX 300
#define APP_BOARD_VOICE_WAKE_ENERGY_PACKETS 2
#define APP_BOARD_VOICE_WAKELESS_FOLLOWUP_ENABLE 0
#define APP_BOARD_VOICE_WAKE_DIRECT_SAMPLES 1600
#define APP_BOARD_VOICE_TASK_STACK_BYTES 12288
